### ISSUE TITLE
Turkish Character Support

### ISSUE THREAD

**Issue by ozgrozer** [twitter/typeahead.js#1309]
I have a json file which has listing city names of Turkey.
Some cities have Turkish letters like İstanbul, İzmir.
When I press **İ** there is no problem all of them listing but when I press **i** there is no result.
I want to list cities which starting **İ** and **I**, when I press **i** too.
How can I fix that?

in English
**i** - **I**

in Turkish
**i** - **İ**
**ı** - **I**

**Comment by osrl** [comment]
Did you find any solution @ozgrozer ?

**Comment by serlogo53** [comment]
sayfa kodlamanızda ve veritabanında utf8 kullanmanızı öneririm. ben bu şekilde sorunu çözdüm.
i prefer use utf8 in db and page. i fixed by this.

**Comment by utkukaynar** [comment]
We're using UTF-8 on both page and db, yet we're still experiencing the issue.

**Comment by JD-V** [comment]
This happens because search algorithm works on characters code values, English 'i' and turkish 'İ' certainly has different character codes. Might need to dig dipper inside the implementation to fix this.
