### ISSUE TITLE
limit it typeahead with multiple datasets doesn't work properly

### ISSUE THREAD

**Issue by Victori0us** [twitter/typeahead.js#1321]
version 0.11.1

when limit sets to 10,  typeahead shows only 2 suggestions (no result for others datasets). From server come 8 suggestions (it  are showing only 2 from 8).

**Comment by rsutphin** [comment]
This sounds like the problem fixed by #1212.

**Comment by Victori0us** [comment]
Typeahead (limit set to 10) use multiple datasets and not use async. If type search word from server come 8 results, but it shows only 2.
![sample](https://cloud.githubusercontent.com/assets/4447685/8718137/53b830ca-2baa-11e5-8355-7332b99b8e68.jpg)

**Comment by Victori0us** [comment]
I have last version, but problem persists. If Typeahead has limit 6, it works perfectly. But if I set limit to 10 Typeahead shows only 2 results from 8 results (from server come).
